In [163]:
from sqlalchemy import create_engine, text
engine = create_engine('postgresql://admin:admin@localhost:5434/investments')
drop_table = ("DROP TABLE IF EXISTS stg_transaction CASCADE")
with engine.begin() as conn :
    conn.execute(text(drop_table))

In [164]:
import pandas as pd

csv_url = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRf1Xxc1wycc2YRWoIEnM7sWXbmKeZ74ZGbTbaE1bhNROHwMe3_5WaqozTQ2WnGed84RPB51bMQfBwb/pub?gid=1509911894&single=true&output=csv'

stg_transaction_df = pd.read_csv(csv_url)
stg_transaction_df['Date'] = pd.to_datetime(stg_transaction_df['Date'])

stg_transaction_df.to_sql('stg_transaction', engine, if_exists='replace', index=False)

35

In [165]:
import yfinance as yf
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine('postgresql://admin:admin@localhost:5434/investments')

tickers = stg_transaction_df['Ticker'].dropna().unique().tolist()

history_df = yf.download(tickers, start="2024-01-02", interval="1wk", group_by='Ticker')

records = []
for ticker in tickers:
    df = history_df[ticker].copy() 
    df = df.reset_index()
    df['Ticker'] = ticker
    records.append(df)

fact_df = pd.concat(records, ignore_index=True)

fact_df.rename(columns=lambda x: x.replace(" ", "_"), inplace=True)


fact_df.to_sql('stg_history', engine, if_exists='replace', index=False)

/var/folders/d_/n324z2xs76d63sdx1pngjl5h0000gn/T/ipykernel_24592/161925544.py:9: FutureWarning: YF.download() has changed argument auto_adjust default to True
  history_df = yf.download(tickers, start="2024-01-02", interval="1wk", group_by='Ticker')
[*********************100%***********************]  9 of 9 completed

900

In [166]:
transaction_dates = stg_transaction_df.copy()
historical_dates = fact_df.copy()
all_dates = pd.concat([transaction_dates, historical_dates], ignore_index=True)

dim_date = all_dates[['Date']]
dim_date.loc[:, 'Date'] = pd.to_datetime(dim_date['Date'])
dim_date = dim_date.drop_duplicates(subset=['Date'])
dim_date = dim_date.sort_values('Date').reset_index(drop=True)

print(len(dim_date))

122

In [167]:
dim_ticker = stg_transaction_df.copy()
dim_ticker = stg_transaction_df[['Ticker']]
dim_ticker = dim_ticker.drop_duplicates()
dim_ticker

   Ticker
0   GOOGL
1     UMC
2   FBNDX
3      PR
4     BAC
6     NVO
21     KO
25  FNILX
26  FZILX

In [168]:
dim_sector = stg_transaction_df.copy()
dim_sector = stg_transaction_df[['Sector']]
dim_sector = dim_sector.drop_duplicates()
dim_sector

          Sector
0     Technology
2          Bonds
3         Energy
4      Financial
6     Healthcare
21      Consumer
25  Mutual Funds

In [169]:
dim_purchase_type = stg_transaction_df.copy()
dim_purchase_type = stg_transaction_df[['Purchase Type']]
dim_purchase_type = dim_purchase_type.drop_duplicates()
dim_purchase_type

  Purchase Type
0          Cash
8     Dividends

In [170]:
drop_dim = [
    "DROP TABLE IF EXISTS dim_date CASCADE;",
    "DROP TABLE IF EXISTS dim_ticker CASCADE;",
    "DROP TABLE IF EXISTS dim_sector CASCADE;",
    "DROP TABLE IF EXISTS dim_purchase_type CASCADE;"
    ]

with engine.begin() as conn:
    for keys in drop_dim :
        conn.execute(text(keys))

In [171]:
dim_date.to_sql('dim_date', engine, if_exists='replace', index=False)
dim_ticker.to_sql('dim_ticker', engine, if_exists='replace', index=False)
dim_sector.to_sql('dim_sector', engine, if_exists='replace', index=False)
dim_purchase_type.to_sql('dim_purchase_type', engine, if_exists='replace', index=False)

2

In [172]:
add_pk = [
"ALTER TABLE dim_date           ADD COLUMN date_id SERIAL PRIMARY KEY",
"ALTER TABLE dim_purchase_type  ADD COLUMN purchase_type_id SERIAL PRIMARY KEY",
"ALTER TABLE dim_ticker         ADD COLUMN ticker_id SERIAL PRIMARY KEY",
"ALTER TABLE dim_sector         ADD COLUMN sector_id SERIAL PRIMARY KEY"   
]
with engine.begin() as conn:
    for pks in add_pk :
        conn.execute(text(pks))

In [173]:
# NEEDS TO BE ADJUSTED FOR PURCHASE TYPE
wh_transaction_sql = """
    select all 
        t.ticker_id,
        d.date_id,
        tr."Number of Shares" as shares,
        s.sector_id,
        p.purchase_type_id,
        tr."Purchase Price" as purchase_price
    from stg_transaction tr
    join dim_ticker t on t."Ticker" = tr."Ticker"
    join dim_date d on d."Date" = tr."Date" 
    join dim_sector s on s."Sector" = tr."Sector"
    join dim_purchase_type p on p."Purchase Type" = tr."Purchase Type";
"""
wh_transaction_df = pd.read_sql(wh_transaction_sql, engine)
wh_transaction_df.head(5)

   ticker_id  date_id  shares  sector_id  purchase_type_id  purchase_price
0          1       11   1.000          1                 1          165.74
1          2       46  15.000          1                 1            7.12
2          4       52  10.000          3                 1           14.66
3          3       52  27.548          2                 1            7.23
4          6       54   1.000          5                 1          109.07

In [174]:
wh_history_sql = """
    select 
        d.date_id,
        t.ticker_id,
        h."Open" as open,
        h."High" as high,
        h."Close" as close,
        h."Volume" as volume
    from stg_history h
    join dim_date d on d."Date" = h."Date" 
    join dim_ticker t on t."Ticker" = h."Ticker"; 
"""

wh_history_df = pd.read_sql(wh_history_sql, engine)
wh_history_df.head(5)

   date_id  ticker_id       open        high       close     volume
0        1          9  10.640781   10.640781   10.582476          0
1        1          8  16.574493   16.574493   16.416170          0
2        1          7  55.811513   57.197308   56.637295   54478900
3        1          6  99.009418  106.086391  103.166046   19811000
4        1          5  31.989706   33.235186   32.986092  171734300

In [175]:
wh_history_df.to_sql('fact_history', engine, if_exists='replace', index=False)

900

In [176]:
wh_transaction_df.to_sql('fact_transaction', engine, if_exists='replace', index=False)

35

In [177]:
add_fk_h = [
"ALTER TABLE fact_history  ADD COLUMN history_id SERIAL PRIMARY KEY",
"ALTER TABLE fact_history  ADD CONSTRAINT fk_date FOREIGN KEY(date_id) REFERENCES dim_date(date_id)",
"ALTER TABLE fact_history  ADD CONSTRAINT fk_ticker FOREIGN KEY(ticker_id) REFERENCES dim_ticker(ticker_id)",
]
with engine.begin() as conn:
    for keys in add_fk_h :
        conn.execute(text(keys))

In [178]:
add_fk_t = [
"ALTER TABLE fact_transaction  ADD COLUMN transaction_id SERIAL PRIMARY KEY",
"ALTER TABLE fact_transaction  ADD CONSTRAINT fk_ticker FOREIGN KEY(ticker_id) REFERENCES dim_ticker(ticker_id)",   
"ALTER TABLE fact_transaction  ADD CONSTRAINT fk_date FOREIGN KEY(date_id) REFERENCES dim_date(date_id)",
"ALTER TABLE fact_transaction  ADD CONSTRAINT fk_sector FOREIGN KEY(sector_id) REFERENCES dim_sector(sector_id)",
"ALTER TABLE fact_transaction  ADD CONSTRAINT fk_purchase_type FOREIGN KEY(purchase_type_id) REFERENCES dim_purchase_type(purchase_type_id)"   

]
with engine.begin() as conn:
    for keys in add_fk_t :
        conn.execute(text(keys))